// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6wPYtMvsjF1hzrYccapnQ7mdxhn9zJWQ',
    appId: '1:816395799112:web:1ba00e8086b8a988f9267d',
    messagingSenderId: '816395799112',
    projectId: 'doctor-appointment-app-d2643',
    authDomain: 'doctor-appointment-app-d2643.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-d2643.appspot.com',
    measurementId: 'G-3D2XQ8JT9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXGbYh5InmwnmdOCymMpfsJsPkn_Hw28',
    appId: '1:816395799112:android:662e8a5941394223f9267d',
    messagingSenderId: '816395799112',
    projectId: 'doctor-appointment-app-d2643',
    storageBucket: 'doctor-appointment-app-d2643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAll78A5PSLw-XSuXmVjQ1UB24EBbh65Cs',
    appId: '1:816395799112:ios:0525d6ff0f081f37f9267d',
    messagingSenderId: '816395799112',
    projectId: 'doctor-appointment-app-d2643',
    storageBucket: 'doctor-appointment-app-d2643.appspot.com',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );
}
